In [55]:
import numpy as np 
import pandas as pd

In [56]:
data = pd.read_csv("Luxury_Products_Apparel_Data.csv")
data.head(5)

Unnamed: 0     Category SubCategory  \
0        8037  Accessories        Bags   
1       13670  Accessories       Socks   
2       13983        Suits     Tuxedos   
3       12081  Accessories      Gloves   
4       15617  Accessories   Cufflinks   

                                         ProductName  \
0                     "Prada Striped Shell Belt Bag"   
1  "Falke - Lhasa Wool And Cashmere-blend Socks -...   
2                    "peak lapel tuxedo suit jacket"   
3                "Thom Browne Navy 4-Bar Rib Gloves"   
4  "Alice Made This - Bayley Round Patina-brass C...   

                                         Description  
0  "One of Prada's most functional designs, this ...  
1  "Falke - Casual yet luxurious, Falke's dark na...  
2  "White and black linen blend peak lapel tuxedo...  
3  "Pair of rib knit cashmere gloves in navy. Sig...  
4  "Alice Made This - Made in the UK, these teal ...

In [57]:
data = data.dropna()

In [58]:
from sklearn.preprocessing import LabelEncoder

labelenchoder = LabelEncoder()

data["Category"] = labelenchoder.fit_transform(data["Category"])

In [59]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(data[["ProductName","Description"]],data["Category"])

In [60]:
vectorcolumns = X_train[["ProductName","Description"]]
vectorcolumns.head(5)

ProductName  \
3454                       "Greg Lauren Borg Long Pant"   
2707  "Ami - Chunky-sole Leather Derby Shoes - Mens ...   
2421  "Valentino Men's Half-Placket Cotton Poplin Po...   
4892      "Isaia Men's Woven Wool Pocket Square - Blue"   
4673  "Men's Greyson Queen Bee Short Sleeve Performa...   

                                            Description  
3454  "Greg Lauren's track pant has a mid rise draws...  
2707  "AMI - AMI reinterprets traditional derby shoe...  
2421  "Cut in an oversized fit, this crisp cotton po...  
4892  "A miniature crosshatch print adorns this soph...  
4673  "Stretchy, moisture-wicking fabric keeps you c...

In [61]:
from sklearn.feature_extraction.text import CountVectorizer

v1 = CountVectorizer(lowercase=True)
v2 = CountVectorizer(lowercase=True)

vectorcolumn_P = v1.fit_transform(vectorcolumns["ProductName"].values)
vectorcolumn_D = v2.fit_transform(vectorcolumns["Description"].values)

In [62]:
vectorcolumn_P_array = vectorcolumn_P.toarray()
vectorcolumn_D_array = vectorcolumn_D.toarray()


In [63]:
vectorcolumn_P_array

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [64]:
vectorcolumn_D_array.shape

(3722, 8708)

In [65]:
vectorcolumn_P_array.shape

(3722, 3314)

In [66]:
train_nlp = np.hstack((vectorcolumn_D_array,vectorcolumn_P_array))
train_nlp.shape

(3722, 12022)

In [67]:
Y_train.value_counts()

0    970
6    772
5    440
1    408
4    382
2    222
9    203
7    143
8    110
3     72
Name: Category, dtype: int64

In [68]:
Y_train.shape

(3722,)

In [69]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(train_nlp,Y_train)

MultinomialNB()

## **TEST**

In [70]:
vectorcolumns_test = X_test[["ProductName","Description"]]
vectorcolumns_test.head()

ProductName  \
363     "Men's Tommy John Second Skin Trunks"   
3769       "Men's Bugatchi Short Sleeve Polo"   
2305            "Men's Formal Douglas Tuxedo"   
1999  "Logo Printed Cotton Jersey Sweatpants"   
3913       "Balenciaga Tuxedo Pants in Black"   

                                            Description  
363   "A branded waistband tops light and breathable...  
3769  "Rich color saturates a spread-collar polo kni...  
2305  "Tom Ford Douglas two-piece formal tuxedo. Pea...  
1999  "Elastic waistband with drawstring. Back print...  
3913  "Balenciaga Tuxedo Pants in Black Self: 91% po...

In [71]:
vectorcolumn_P_t = v1.transform(["Prada Striped Shell Belt Bag"])  #(vectorcolumns_test["ProductName"].values)
vectorcolumn_D_t = v2.transform(["One of Prada's most functional designs, this belt bag is made from weather-resistant shell fabric with zip compartments for storing your daily belongings. It's"]) #(vectorcolumns_test["Description"].values)

In [72]:
vectorcolumn_P_t_array = vectorcolumn_P_t.toarray()
vectorcolumn_D_t_array = vectorcolumn_D_t.toarray()

In [73]:
vectorcolumn_P_t_array.shape

(1, 3314)

In [74]:
vectorcolumn_D_t_array.shape

(1, 8708)

In [75]:
test_nlp = np.hstack((vectorcolumn_D_t_array,vectorcolumn_P_t_array))
test_nlp.shape

(1, 12022)

In [76]:
from sklearn.metrics import classification_report

y_pred = model.predict(test_nlp)
y_pred

array([0])

In [77]:
model.predict_proba(test_nlp)

array([[9.99999846e-01, 1.20101193e-11, 9.45550713e-08, 9.82699111e-15,
        5.97724697e-08, 7.81431361e-13, 9.08923570e-12, 9.09958577e-14,
        1.18101026e-15, 4.22769802e-13]])